#include <iostream>
#include <sqlite3.h>
using namespace std;

int main() {
    sqlite3* db;
    char* errMsg = 0;

    int run = sqlite3_open("database.db", &db);
    if (run)
    {
        cerr << "Cant open file.db:" << sqlite3_errmsg(db); 
    }
    
    const char* sql =   R"(
                        CREATE TABLE IF NOT EXISTS student (
                        studentId INTEGER PRIMARY KEY AUTOINCREMENT,
                        mssv TEXT NOT NULL,
                        name TEXT NOT NULL,
                        age INTEGER NOT NULL,
                        hometown TEXT NOT NULL,
                        email TEXT NOT NULL);

                        create table if not exists major(
                        majorId integer primary key autoincrement,
                        majorName text not null);

                        create table if not exists course(
                        courseId    integer     primary key autoincrement       ,
                        courseName  text        not null                        ,
                        majorId     integer     not null                        ,
                        foreign key (majorId) references major(majorId));
                        
                        create table if not exists class(
                        classId     integer     primary key autoincrement               ,
                        courseId    integer     not null                                ,
                        classCode   text        unquie not null                         ,
                        semesterId  integer     unique                                  ,
                        foreign key (courseId)      references  course   (courseId)     ,
                        foreign key (semesterId)    references  semester (semesterId)   );

                        create table if not exists score(
                        studentId       integer     primary key     autoincrement       ,
                        processScore    real                                            ,
                        endOfCourse     real                                            ,
                        foreign key     (studentId) references student(studentId)       );

                        create table if not exists studentCourse(
                        classId         integer                                             , 
                        studentId       integer                                             ,
                        status          text        not null                                ,
                        primary key     (studentId,classId)                                 ,
                        foreign key     (studentId)     references   student (studentId)    ,
                        foreign key     (classId)       references   class   (classId)      );

                        create table if not exists semester(
                        semesterId      integer primary key autoincrement   ,
                        semesterNumber  integer not null                    ,
                        year            integer not null                    );

                        create table if not exists classSchedule(
                        classId         integer     primary key autoincrement   ,
                        dayOfWeek       integer     not null                    ,
                        room            text        not null                    ,
                        startPeriod     integer     not null                    ,
                        numberPeriod    integer     not null                    ,
                        foreign key (classId) references    class(classId)      );
                        
                        
                        INSERT INTO student (mssv, name, age, hometown, email) VALUES
                        ('A1B01', 'Nguyễn Văn An', 18,  'Hà Nội', 'an123@gmail.com'),
                        ('B2C02', 'Trần Thị Bình', 18,  'TP. Hồ Chí Minh', 'binh456@gmail.com'),
                        ('C3D03', 'Lê Hoàng Cường', 18,  'Đà Nẵng', 'cuong789@gmail.com'),
                        ('D4E04', 'Phạm Minh Đức', 18,  'Nghệ An', 'duc101@gmail.com'),
                        ('E5F05', 'Hoàng Thu Giang', 18,  'Thanh Hóa', 'giang202@gmail.com'),
                        ('F6G06', 'Vũ Quốc Hải', 18,  'Hải Phòng', 'hai303@gmail.com'),
                        ('G7H07', 'Đặng Mai Hương', 18,  'Thừa Thiên Huế', 'huong404@gmail.com'),
                        ('H8I08', 'Bùi Tuấn Kiệt', 18,  'Cần Thơ', 'kiet505@gmail.com'),
                        ('I9J09', 'Đỗ Thùy Linh', 18,  'Quảng Ninh', 'linh606@gmail.com'),
                        ('J0K10', 'Hồ Nam Phong', 18,  'Đắk Lắk', 'phong707@gmail.com'),
                        ('K1L11', 'Ngo Thi Bich', 18,  'Lâm Đồng', 'bich808@gmail.com'),
                        ('L2M12', 'Dương Văn Quân', 18,  'Đồng Nai', 'quan909@gmail.com'),
                        ('M3N13', 'Lý Ngọc Sơn', 18,  'Bình Dương', 'son111@gmail.com'),
                        ('N4O14', 'Đoàn Bảo Trang', 18,  'Khánh Hòa', 'trang222@gmail.com'),
                        ('O5P15', 'Trịnh Anh Tú', 18,  'Hà Tĩnh', 'tu333@gmail.com'),
                        ('P6Q16', 'Mai Xuân Vinh', 18,  'Thái Bình', 'vinh444@gmail.com'),
                        ('Q7R17', 'Phan Kim Yến', 18,  'Nam Định', 'yen555@gmail.com'),
                        ('R8S18', 'Nguyễn Tiến Đạt', 18,  'Bắc Ninh', 'dat666@gmail.com'),
                        ('S9T19', 'Trần Bảo Ngọc', 18,  'Vĩnh Phúc', 'ngoc777@gmail.com'),
                        ('T0U20', 'Lê Hữu Phước', 18,  'Hải Dương', 'phuoc888@gmail.com'),
                        ('U1V21', 'Phạm Quỳnh Anh', 18,  'Kiên Giang', 'anh999@gmail.com'),
                        ('V2W22', 'Hoàng Trọng Hiếu', 18,  'An Giang', 'hieu124@gmail.com'),
                        ('W3X23', 'Vũ Thị Hòa', 18,  'Tiền Giang', 'hoa235@gmail.com'),
                        ('X4Y24', 'Đặng Văn Hùng', 18,  'Long An', 'hung346@gmail.com'),
                        ('Y5Z25', 'Bùi Thị Khanh', 18,  'Bến Tre', 'khanh457@gmail.com'),
                        ('Z6A26', 'Đỗ Quang Long', 18,  'Quảng Nam', 'long568@gmail.com'),
                        ('A7B27', 'Hồ Thị Mỹ', 18,  'Quảng Ngãi', 'my679@gmail.com'),
                        ('B8C28', 'Nghiem Van Nam', 18,  'Bình Định', 'nam780@gmail.com'),
                        ('C9D29', 'Dương Khánh Oanh', 18,  'Phú Yên', 'oanh891@gmail.com'),
                        ('D0E30', 'Lý Tấn Phát', 18,  'Gia Lai', 'phat902@gmail.com'),
                        ('E1F31', 'Đoàn Văn Phúc', 18,  'Kon Tum', 'phuc113@gmail.com'),
                        ('F2G32', 'Trịnh Thị Quyên', 18,  'Sóc Trăng', 'quyen224@gmail.com'),
                        ('G3H33', 'Mai Hoàng Sang', 18,  'Cà Mau', 'sang335@gmail.com'),
                        ('H4I34', 'Phan Minh Tâm', 18,  'Bạc Liêu', 'tam446@gmail.com'),
                        ('I5J35', 'Nguyễn Thị Thảo', 18,  'Trà Vinh', 'thao557@gmail.com'),
                        ('J6K36', 'Trần Hữu Thịnh', 18,  'Vĩnh Long', 'thinh668@gmail.com'),
                        ('K7L37', 'Lê Ngọc Thủy', 18,  'Hậu Giang', 'thuy779@gmail.com'),
                        ('L8M38', 'Phạm Quốc Trung', 18,  'Đồng Tháp', 'trung880@gmail.com'),
                        ('M9N39', 'Hoàng Văn Uy', 18,  'Bà Rịa - Vũng Tàu', 'uy991@gmail.com'),
                        ('N0O40', 'Vũ Khánh Vân', 18,  'Bình Thuận', 'van102@gmail.com'),
                        ('O1P41', 'Đặng Thanh Vũ', 18,  'Ninh Thuận', 'vu213@gmail.com'),
                        ('P2Q42', 'Bùi Văn Trọng', 18,  'Bình Phước', 'trong324@gmail.com'),
                        ('Q3R43', 'Đỗ Minh Trí', 18,  'Tây Ninh', 'tri435@gmail.com'),
                        ('R4S44', 'Hồ Xuân Trường', 18,  'Hưng Yên', 'truong546@gmail.com'),
                        ('S5T45', 'Ngô Văn Tùng', 18,  'Hà Nam', 'tung657@gmail.com'),
                        ('T6U46', 'Dương Thị Tươi', 18,  'Ninh Bình', 'tuoi768@gmail.com'),
                        ('U7V47', 'Lý Kim Anh', 18,  'Hòa Bình', 'anh879@gmail.com'),
                        ('V8W48', 'Đoàn Minh Bảo', 18,  'Sơn La', 'bao980@gmail.com'),
                        ('W9X49', 'Trịnh Văn Chiến', 18,  'Điện Biên', 'chien191@gmail.com'),
                        ('X0Y50', 'Mai Thị Dung', 18,  'Lai Châu', 'dung202@gmail.com'),
                        ('Y1Z51', 'Phan Văn Giang', 18,  'Lào Cai', 'giang313@gmail.com'),
                        ('Z2A52', 'Nguyễn Thị Hải', 18,  'Yên Bái', 'hai424@gmail.com'),
                        ('A3B53', 'Trần Hữu Hùng', 18,  'Thái Nguyên', 'hung535@gmail.com'),
                        ('B4C54', 'Lê Thi Hương', 18,  'Bắc Giang', 'huong646@gmail.com'),
                        ('C5D55', 'Phạm Văn Khoa', 18,  'Phú Thọ', 'khoa757@gmail.com'),
                        ('D6E56', 'Hoàng Thị Lâm', 18,  'Tuyên Quang', 'lam868@gmail.com'),
                        ('E7F57', 'Vũ Văn Mạnh', 18,  'Hà Giang', 'manh979@gmail.com'),
                        ('F8G58', 'Đặng Thị Nga', 18,  'Cao Bằng', 'nga180@gmail.com'),
                        ('G9H59', 'Bùi Văn Phong', 18,  'Lạng Sơn', 'phong291@gmail.com'),
                        ('H0I60', 'Đỗ Thị Phương', 18,  'Bắc Kạn', 'phuong402@gmail.com'),
                        ('I1J61', 'Hồ Văn Bằng', 18,  'Quảng Bình', 'bang513@gmail.com'),
                        ('J2K62', 'Ngô Thị Cúc', 18,  'Quảng Trị', 'cuc624@gmail.com'),
                        ('K3L63', 'Dương Văn Danh', 18,  'Hà Nội', 'danh735@gmail.com'),
                        ('L4M64', 'Lý Thị Đào', 18,  'TP. Hồ Chí Minh', 'dao846@gmail.com'),
                        ('M5N65', 'Đoàn Văn Điệp', 18,  'Đà Nẵng', 'diep957@gmail.com'),
                        ('N6O66', 'Trịnh Thị Hạnh', 18,  'Nghệ An', 'hanh168@gmail.com'),
                        ('O7P67', 'Mai Văn Hoàng', 18,  'Thanh Hóa', 'hoang279@gmail.com'),
                        ('P8Q68', 'Phan Thị Khang', 18,  'Hải Phòng', 'khang390@gmail.com'),
                        ('Q9R69', 'Nguyễn Văn Lộc', 18,  'Thừa Thiên Huế', 'loc501@gmail.com'),
                        ('R0S70', 'Trần Thị Mai', 18,  'Cần Thơ', 'mai612@gmail.com'),
                        ('S1T71', 'Lê Văn Nghĩa', 18,  'Quảng Ninh', 'nghia723@gmail.com'),
                        ('T2U72', 'Phạm Thị Nhung', 18,  'Đắk Lắk', 'nhung834@gmail.com'),
                        ('U3V73', 'Hoàng Văn Phát', 18,  'Lâm Đồng', 'phat945@gmail.com'),
                        ('V4W74', 'Vũ Thị Quyên', 18,  'Đồng Nai', 'quyen156@gmail.com'),
                        ('W5X75', 'Đặng Văn Sang', 18,  'Bình Dương', 'sang267@gmail.com'),
                        ('X6Y76', 'Bùi Thị Sơn', 18,  'Khánh Hòa', 'son378@gmail.com'),
                        ('Y7Z77', 'Đỗ Văn Thái', 18,  'Hà Tĩnh', 'thai489@gmail.com'),
                        ('Z8A78', 'Hồ Thị Thơ', 18,  'Thái Bình', 'tho600@gmail.com'),
                        ('A9B79', 'Ngô Văn Tiến', 18,  'Nam Định', 'tien711@gmail.com'),
                        ('B0C80', 'Dương Thị Trang', 18,  'Bắc Ninh', 'trang822@gmail.com'),
                        ('C1D81', 'Lý Văn Tú', 18,  'Vĩnh Phúc', 'tu933@gmail.com'),
                        ('D2E82', 'Đoàn Thị Vân', 18,  'Hải Dương', 'van144@gmail.com'),
                        ('E3F83', 'Trịnh Văn Xuân', 18,  'Kiên Giang', 'xuan255@gmail.com'),
                        ('F4G84', 'Mai Thị Yến', 18,  'An Giang', 'yen366@gmail.com'),
                        ('G5H85', 'Phan Văn Ân', 18,  'Tiền Giang', 'an477@gmail.com'),
                        ('H6I86', 'Nguyễn Thị Bình', 18,  'Long An', 'binh588@gmail.com'),
                        ('I7J87', 'Trần Văn Cường', 18,  'Bến Tre', 'cuong699@gmail.com'),
                        ('J8K88', 'Lê Thị Duyên', 18,  'Quảng Nam', 'duyen810@gmail.com'),
                        ('K9L89', 'Phạm Văn Giang', 18,  'Quảng Ngãi', 'giang921@gmail.com'),
                        ('L0M90', 'Hoàng Thị Hiền', 18,  'Bình Định', 'hien132@gmail.com'),
                        ('M1N91', 'Vũ Văn Huy', 18,  'Phú Yên', 'huy243@gmail.com'),
                        ('N2O92', 'Đặng Thị Khánh', 18,  'Gia Lai', 'khanh354@gmail.com'),
                        ('O3P93', 'Bùi Văn Liêm', 18,  'Kon Tum', 'liem465@gmail.com'),
                        ('P4Q94', 'Đỗ Thị Minh', 18,  'Sóc Trăng', 'minh576@gmail.com'),
                        ('Q5R95', 'Hồ Văn Nam', 18,  'Cà Mau', 'nam687@gmail.com'),
                        ('R6S96', 'Ngô Thị Nga', 18,  'Bạc Liêu', 'nga798@gmail.com'),
                        ('S7T97', 'Dương Văn Quý', 18,  'Trà Vinh', 'quy909@gmail.com'),
                        ('T8U98', 'Lý Thị Tâm', 18,  'Vĩnh Long', 'tam120@gmail.com'),
                        ('U9V99', 'Đoàn Văn Tấn', 18,  'Hậu Giang', 'tan231@gmail.com'),
                        ('V0W00', 'Trịnh Thị Thu', 18,  'Đồng Tháp', 'thu342@gmail.com'),
                        ('W1X01', 'Mai Văn Toàn', 18,  'Bà Rịa - Vũng Tàu', 'toan453@gmail.com'),
                        ('X2Y02', 'Phan Thị Tuyết', 18,  'Bình Thuận', 'tuyet564@gmail.com'),
                        ('Y3Z03', 'Nguyễn Văn Việt', 18,  'Ninh Thuận', 'viet675@gmail.com'),
                        ('Z4A04', 'Trần Thị Vượng', 18,  'Bình Phước', 'vuong786@gmail.com'),
                        ('A5B05', 'Lê Văn An', 18,  'Tây Ninh', 'an897@gmail.com'),
                        ('B6C06', 'Phạm Thị Bích', 18,  'Hưng Yên', 'bich008@gmail.com'),
                        ('C7D07', 'Hoàng Văn Chiến', 18,  'Hà Nam', 'chien119@gmail.com'),
                        ('D8E08', 'Vũ Thị Diệp', 18,  'Ninh Bình', 'diep230@gmail.com'),
                        ('E9F09', 'Đặng Văn Dũng', 18,  'Hòa Bình', 'dung341@gmail.com'),
                        ('F0G10', 'Bùi Thị Hà', 18,  'Sơn La', 'ha452@gmail.com'),
                        ('G1H11', 'Đỗ Văn Hải', 18,  'Điện Biên', 'hai563@gmail.com'),
                        ('H2I12', 'Hồ Thị Hằng', 18,  'Lai Châu', 'hang674@gmail.com'),
                        ('I3J13', 'Ngô Văn Hiếu', 18,  'Lào Cai', 'hieu785@gmail.com'),
                        ('J4K14', 'Dương Thị Hoa', 18,  'Yên Bái', 'hoa896@gmail.com'),
                        ('K5L15', 'Lý Văn Hùng', 18,  'Thái Nguyên', 'hung007@gmail.com'),
                        ('L6M16', 'Đoàn Thị Hương', 18,  'Bắc Giang', 'huong118@gmail.com'),
                        ('M7N17', 'Trịnh Văn Khánh', 18,  'Phú Thọ', 'khanh229@gmail.com'),
                        ('N8O18', 'Mai Thị Lan', 18,  'Tuyên Quang', 'lan340@gmail.com'),
                        ('O9P19', 'Phan Văn Lâm', 18,  'Hà Giang', 'lam451@gmail.com'),
                        ('P0Q20', 'Nguyễn Thị Linh', 18,  'Cao Bằng', 'linh562@gmail.com'),
                        ('Q1R21', 'Trần Văn Long', 18,  'Lạng Sơn', 'long673@gmail.com'),
                        ('R2S22', 'Lê Thị Mai', 18,  'Bắc Kạn', 'mai784@gmail.com'),
                        ('S3T23', 'Phạm Văn Minh', 18,  'Quảng Bình', 'minh895@gmail.com'),
                        ('T4U24', 'Hoàng Thị Ngân', 18,  'Quảng Trị', 'ngan006@gmail.com'),
                        ('U5V25', 'Vũ Văn Ngọc', 18,  'Hà Nội', 'ngoc117@gmail.com'),
                        ('V6W26', 'Đặng Thị Nhung', 18,  'TP. Hồ Chí Minh', 'nhung228@gmail.com'),
                        ('W7X27', 'Bùi Văn Phong', 18,  'Đà Nẵng', 'phong339@gmail.com'),
                        ('X8Y28', 'Đỗ Thị Phượng', 18,  'Nghệ An', 'phuong450@gmail.com'),
                        ('Y9Z29', 'Hồ Văn Quân', 18,  'Thanh Hóa', 'quan561@gmail.com'),
                        ('Z0A30', 'Ngô Thị Quyên', 18,  'Hải Phòng', 'quyen672@gmail.com'),
                        ('A1B31', 'Dương Văn Sơn', 18,  'Thừa Thiên Huế', 'son783@gmail.com'),
                        ('B2C32', 'Lý Thị Thảo', 18,  'Cần Thơ', 'thao894@gmail.com'),
                        ('C3D33', 'Đoàn Văn Thịnh', 18,  'Quảng Ninh', 'thinh005@gmail.com'),
                        ('D4E34', 'Trịnh Thị Trang', 18,  'Đắk Lắk', 'trang116@gmail.com'),
                        ('E5F35', 'Mai Văn Tuấn', 18,  'Lâm Đồng', 'tuan227@gmail.com'),
                        ('F6G36', 'Phan Thị Tuyết', 18,  'Đồng Nai', 'tuyet338@gmail.com'),
                        ('G7H37', 'Nguyễn Văn Vinh', 18,  'Bình Dương', 'vinh449@gmail.com'),
                        ('H8I38', 'Trần Thị Yến', 18,  'Khánh Hòa', 'yen560@gmail.com'),
                        ('I9J39', 'Lê Văn Anh', 18,  'Hà Tĩnh', 'anh671@gmail.com'),
                        ('J0K40', 'Phạm Thị Bảo', 18,  'Thái Bình', 'bao782@gmail.com'),
                        ('K1L41', 'Hoàng Văn Cường', 18,  'Nam Định', 'cuong893@gmail.com'),
                        ('L2M42', 'Vũ Thị Dung', 18,  'Bắc Ninh', 'dung004@gmail.com'),
                        ('M3N43', 'Đặng Văn Đức', 18,  'Vĩnh Phúc', 'duc115@gmail.com'),
                        ('N4O44', 'Bùi Thị Giang', 18,  'Hải Dương', 'giang226@gmail.com'),
                        ('O5P45', 'Đỗ Văn Hải', 18,  'Kiên Giang', 'hai337@gmail.com'),
                        ('P6Q46', 'Hồ Thị Hoa', 18,  'An Giang', 'hoa448@gmail.com'),
                        ('Q7R47', 'Ngô Văn Hung', 18,  'Tiền Giang', 'hung559@gmail.com'),
                        ('R8S48', 'Dương Thị Hương', 18,  'Long An', 'huong670@gmail.com'),
                        ('S9T49', 'Lý Văn Khoa', 18,  'Bến Tre', 'khoa781@gmail.com'),
                        ('T0U50', 'Đoàn Thị Lâm', 18,  'Quảng Nam', 'lam892@gmail.com'),
                        ('U1V51', 'Trịnh Văn Linh', 18,  'Quảng Ngãi', 'linh003@gmail.com'),
                        ('V2W52', 'Mai Thị Mai', 18,  'Bình Định', 'mai114@gmail.com'),
                        ('W3X53', 'Phan Văn Nam', 18,  'Phú Yên', 'nam225@gmail.com'),
                        ('X4Y54', 'Nguyễn Thị Nga', 18,  'Gia Lai', 'nga336@gmail.com'),
                        ('Y5Z55', 'Trần Văn Phong', 18,  'Kon Tum', 'phong447@gmail.com'),
                        ('Z6A56', 'Lê Thị Phương', 18,  'Sóc Trăng', 'phuong558@gmail.com'),
                        ('A7B57', 'Phạm Văn Quân', 18,  'Cà Mau', 'quan669@gmail.com'),
                        ('B8C58', 'Hoàng Thị Quyên', 18,  'Bạc Liêu', 'quyen780@gmail.com'),
                        ('C9D59', 'Vũ Văn Sơn', 18,  'Trà Vinh', 'son891@gmail.com'),
                        ('D0E60', 'Đặng Thị Tâm', 18,  'Vĩnh Long', 'tam002@gmail.com'),
                        ('E1F61', 'Bùi Văn Thái', 18,  'Hậu Giang', 'thai113@gmail.com'),
                        ('F2G62', 'Đỗ Thị Thảo', 18,  'Đồng Tháp', 'thao224@gmail.com'),
                        ('G3H63', 'Hồ Văn Thịnh', 18,  'Bà Rịa - Vũng Tàu', 'thinh335@gmail.com'),
                        ('H4I64', 'Ngô Thị Thu', 18,  'Bình Thuận', 'thu446@gmail.com'),
                        ('I5J65', 'Dương Văn Tiến', 18,  'Ninh Thuận', 'tien557@gmail.com'),
                        ('J6K66', 'Lý Thị Trang', 18,  'Bình Phước', 'trang668@gmail.com'),
                        ('K7L67', 'Đoàn Văn Tú', 18,  'Tây Ninh', 'tu779@gmail.com'),
                        ('L8M68', 'Trịnh Thị Vân', 18,  'Hưng Yên', 'van890@gmail.com'),
                        ('M9N69', 'Mai Văn Vinh', 18,  'Hà Nam', 'vinh001@gmail.com'),
                        ('N0O70', 'Phan Thị Yến', 18,  'Ninh Bình', 'yen112@gmail.com'),
                        ('O1P71', 'Nguyễn Văn An', 18,  'Hòa Bình', 'an223@gmail.com'),
                        ('P2Q72', 'Trần Thị Bình', 18,  'Sơn La', 'binh334@gmail.com'),
                        ('Q3R73', 'Lê Văn Cường', 18,  'Điện Biên', 'cuong445@gmail.com'),
                        ('R4S74', 'Phạm Thị Dung', 18,  'Lai Châu', 'dung556@gmail.com'),
                        ('S5T75', 'Hoàng Văn Giang', 18,  'Lào Cai', 'giang667@gmail.com'),
                        ('T6U76', 'Vũ Thị Hải', 18,  'Yên Bái', 'hai778@gmail.com'),
                        ('U7V77', 'Đặng Văn Hùng', 18,  'Thái Nguyên', 'hung889@gmail.com'),
                        ('V8W78', 'Bùi Thị Hương', 18,  'Bắc Giang', 'huong000@gmail.com'),
                        ('W9X79', 'Đỗ Văn Khánh', 18,  'Phú Thọ', 'khanh111@gmail.com'),
                        ('X0Y80', 'Hồ Thị Lan', 18,  'Tuyên Quang', 'lan222@gmail.com'),
                        ('Y1Z81', 'Ngô Văn Linh', 18, 'Hà Giang', 'linh333@gmail.com'),
                        ('Z2A82', 'Dương Thị Mai', 18, 'Cao Bằng', 'mai444@gmail.com'),
                        ('A3B83', 'Lý Văn Nam', 18, 'Lạng Sơn', 'nam555@gmail.com'),
                        ('B4C84', 'Đoàn Thị Nga', 18, 'Bắc Kạn', 'nga666@gmail.com'),
                        ('C5D85', 'Trịnh Văn Phong', 18, 'Quảng Bình', 'phong777@gmail.com'),
                        ('D6E86', 'Mai Thị Phương', 18, 'Quảng Trị', 'phuong888@gmail.com'),
                        ('E7F87', 'Phan Văn Quân', 18, 'Hà Nội', 'quan999@gmail.com'),
                        ('F8G88', 'Nguyễn Thị Quyên', 18, 'TP. Hồ Chí Minh', 'quyen120@gmail.com'),
                        ('G9H89', 'Trần Văn Sơn', 18, 'Đà Nẵng', 'son231@gmail.com'),
                        ('H0I90', 'Lê Thị Thảo', 18, 'Nghệ An', 'thao342@gmail.com'),
                        ('I1J91', 'Phạm Văn Thịnh', 18, 'Thanh Hóa', 'thinh453@gmail.com'),
                        ('J2K92', 'Hoàng Thị Trang', 18, 'Hải Phòng', 'trang564@gmail.com'),
                        ('K3L93', 'Vũ Văn Tuấn', 18, 'Thừa Thiên Huế', 'tuan675@gmail.com'),
                        ('L4M94', 'Đặng Thị Tuyết', 18, 'Cần Thơ', 'tuyet786@gmail.com'),
                        ('M5N95', 'Bùi Văn Vinh', 18, 'Quảng Ninh', 'vinh897@gmail.com'),
                        ('N6O96', 'Đỗ Thị Yến', 18, 'Đắk Lắk', 'yen008@gmail.com'),
                        ('O7P97', 'Hồ Văn Anh', 18, 'Lâm Đồng', 'anh119@gmail.com'),
                        ('P8Q98', 'Ngô Thị Bảo', 18, 'Đồng Nai', 'bao230@gmail.com'),
                        ('Q9R99', 'Dương Văn Cường', 18, 'Bình Dương', 'cuong341@gmail.com'),
                        ('R0S00', 'Lý Thị Dung', 18, 'Khánh Hòa', 'dung452@gmail.com'),
                        ('S1T01', 'Đoàn Văn Đức', 18, 'Hà Tĩnh', 'duc563@gmail.com'),
                        ('T2U02', 'Trịnh Thị Giang', 18, 'Thái Bình', 'giang674@gmail.com'),
                        ('U3V03', 'Mai Văn Hải', 18, 'Nam Định', 'hai785@gmail.com'),
                        ('V4W04', 'Phan Thị Hoa', 18, 'Bắc Ninh', 'hoa896@gmail.com'),
                        ('W5X05', 'Nguyễn Văn Hùng', 18, 'Vĩnh Phúc', 'hung007@gmail.com'),
                        ('X6Y06', 'Trần Thị Hương', 18, 'Hải Dương', 'huong118@gmail.com'),
                        ('Y7Z07', 'Lê Văn Khoa', 18, 'Kiên Giang', 'khoa229@gmail.com'),
                        ('Z8A08', 'Phạm Thị Lâm', 18, 'An Giang', 'lam340@gmail.com'),
                        ('A9B09', 'Hoàng Văn Linh', 18, 'Tiền Giang', 'linh451@gmail.com'),
                        ('B0C10', 'Vũ Thị Mai', 18, 'Long An', 'mai562@gmail.com'),
                        ('C1D11', 'Đặng Văn Nam', 18, 'Bến Tre', 'nam673@gmail.com'),
                        ('D2E12', 'Bùi Thị Nga', 18, 'Quảng Nam', 'nga784@gmail.com'),
                        ('E3F13', 'Đỗ Văn Phong', 18, 'Quảng Ngãi', 'phong895@gmail.com'),
                        ('F4G14', 'Hồ Thị Phương', 18, 'Bình Định', 'phuong006@gmail.com'),
                        ('G5H15', 'Ngô Văn Quân', 18, 'Phú Yên', 'quan117@gmail.com'),
                        ('H6I16', 'Dương Thị Quyên', 18, 'Gia Lai', 'quyen228@gmail.com'),
                        ('I7J17', 'Lý Văn Sơn', 18, 'Kon Tum', 'son339@gmail.com'),
                        ('J8K18', 'Đoàn Thị Thảo', 18, 'Sóc Trăng', 'thao450@gmail.com'),
                        ('K9L19', 'Trịnh Văn Thịnh', 18, 'Cà Mau', 'thinh561@gmail.com'),
                        ('L0M20', 'Mai Thị Trang', 18, 'Bạc Liêu', 'trang672@gmail.com'),
                        ('M1N21', 'Phan Văn Tuấn', 18, 'Trà Vinh', 'tuan783@gmail.com'),
                        ('N2O22', 'Nguyễn Thị Tuyết', 18, 'Vĩnh Long', 'tuyet894@gmail.com'),
                        ('O3P23', 'Trần Văn Vinh', 18, 'Hậu Giang', 'vinh005@gmail.com'),
                        ('P4Q24', 'Lê Thị Yến', 18, 'Đồng Tháp', 'yen116@gmail.com'),
                        ('Q5R25', 'Phạm Văn An', 18, 'Bà Rịa - Vũng Tàu', 'an227@gmail.com'),
                        ('R6S26', 'Hoàng Thị Bình', 18, 'Bình Thuận', 'binh338@gmail.com'),
                        ('S7T27', 'Vũ Văn Cường', 18, 'Ninh Thuận', 'cuong449@gmail.com'),
                        ('T8U28', 'Đặng Thị Dung', 18, 'Bình Phước', 'dung560@gmail.com'),
                        ('U9V29', 'Bùi Văn Giang', 18, 'Tây Ninh', 'giang671@gmail.com'),
                        ('V0W30', 'Đỗ Thị Hải', 18, 'Hưng Yên', 'hai782@gmail.com'),
                        ('W1X31', 'Hồ Văn Hùng', 18, 'Hà Nam', 'hung893@gmail.com'),
                        ('X2Y32', 'Ngô Thị Hương', 18, 'Ninh Bình', 'huong004@gmail.com'),
                        ('Y3Z33', 'Dương Văn Khánh', 18, 'Hòa Bình', 'khanh115@gmail.com'),
                        ('Z4A34', 'Lý Thị Lan', 18, 'Sơn La', 'lan226@gmail.com'),
                        ('A5B35', 'Đoàn Văn Linh', 18, 'Điện Biên', 'linh337@gmail.com'),
                        ('B6C36', 'Trịnh Thị Mai', 18, 'Lai Châu', 'mai448@gmail.com'),
                        ('C7D37', 'Mai Văn Nam', 18, 'Lào Cai', 'nam559@gmail.com'),
                        ('D8E38', 'Phan Thị Nga', 18, 'Yên Bái', 'nga670@gmail.com'),
                        ('E9F39', 'Nguyễn Văn Phong', 18, 'Thái Nguyên', 'phong781@gmail.com'),
                        ('F0G40', 'Trần Thị Phương', 18, 'Bắc Giang', 'phuong892@gmail.com'),
                        ('G1H41', 'Lê Văn Quân', 18, 'Phú Thọ', 'quan003@gmail.com'),
                        ('H2I42', 'Phạm Thị Quyên', 18, 'Tuyên Quang', 'quyen114@gmail.com'),
                        ('I3J43', 'Hoàng Văn Sơn', 18, 'Hà Giang', 'son225@gmail.com'),
                        ('J4K44', 'Vũ Thị Thảo', 18, 'Cao Bằng', 'thao336@gmail.com'),
                        ('K5L45', 'Đặng Văn Thịnh', 18, 'Lạng Sơn', 'thinh447@gmail.com'),
                        ('L6M46', 'Bùi Thị Trang', 18, 'Bắc Kạn', 'trang558@gmail.com'),
                        ('M7N47', 'Đỗ Văn Tuấn', 18, 'Quảng Bình', 'tuan669@gmail.com'),
                        ('N8O48', 'Hồ Thị Tuyết', 18, 'Quảng Trị', 'tuyet780@gmail.com'),
                        ('O9P49', 'Ngô Văn Vinh', 18, 'Hà Nội', 'vinh891@gmail.com'),
                        ('P0Q50', 'Dương Thị Yến', 18, 'TP. Hồ Chí Minh', 'yen002@gmail.com'),
                        ('Q1R51', 'Lý Văn Anh', 18, 'Đà Nẵng', 'anh113@gmail.com'),
                        ('R2S52', 'Đoàn Thị Bảo', 18, 'Nghệ An', 'bao224@gmail.com'),
                        ('S3T53', 'Trịnh Văn Cường', 18, 'Thanh Hóa', 'cuong335@gmail.com'),
                        ('T4U54', 'Mai Thị Dung', 18, 'Hải Phòng', 'dung446@gmail.com'),
                        ('U5V55', 'Phan Văn Giang', 18, 'Thừa Thiên Huế', 'giang557@gmail.com'),
                        ('V6W56', 'Nguyễn Thị Hải', 18, 'Cần Thơ', 'hai668@gmail.com'),
                        ('W7X57', 'Trần Văn Hùng', 18, 'Quảng Ninh', 'hung779@gmail.com'),
                        ('X8Y58', 'Lê Thị Hương', 18, 'Đắk Lắk', 'huong890@gmail.com'),
                        ('Y9Z59', 'Phạm Văn Khoa', 18, 'Lâm Đồng', 'khoa001@gmail.com'),
                        ('Z0A60', 'Hoàng Thị Lâm', 18, 'Đồng Nai', 'lam112@gmail.com'),
                        ('A1B61', 'Vũ Văn Linh', 18, 'Bình Dương', 'linh223@gmail.com'),
                        ('B2C62', 'Đặng Thị Mai', 18, 'Khánh Hòa', 'mai334@gmail.com'),
                        ('C3D63', 'Bùi Văn Nam', 18, 'Hà Tĩnh', 'nam445@gmail.com'),
                        ('D4E64', 'Đỗ Thị Nga', 18, 'Thái Bình', 'nga556@gmail.com'),
                        ('E5F65', 'Hồ Văn Phong', 18, 'Nam Định', 'phong667@gmail.com'),
                        ('F6G66', 'Ngô Thị Phương', 18, 'Bắc Ninh', 'phuong778@gmail.com'),
                        ('G7H67', 'Dương Văn Quân', 18, 'Vĩnh Phúc', 'quan889@gmail.com'),
                        ('H8I68', 'Lý Thị Quyên', 18, 'Hải Dương', 'quyen000@gmail.com'),
                        ('I9J69', 'Đoàn Văn Sơn', 18, 'Kiên Giang', 'son111@gmail.com'),
                        ('J0K70', 'Trịnh Thị Thảo', 18, 'An Giang', 'thao222@gmail.com'),
                        ('K1L71', 'Mai Văn Thịnh', 18, 'Tiền Giang', 'thinh333@gmail.com'),
                        ('L2M72', 'Phan Thị Trang', 18, 'Long An', 'trang444@gmail.com'),
                        ('M3N73', 'Nguyễn Văn Tuấn', 18, 'Bến Tre', 'tuan555@gmail.com'),
                        ('N4O74', 'Trần Thị Tuyết', 18, 'Quảng Nam', 'tuyet666@gmail.com'),
                        ('O5P75', 'Lê Văn Vinh', 18, 'Quảng Ngãi', 'vinh777@gmail.com'),
                        ('P6Q76', 'Phạm Thị Yến', 18, 'Bình Định', 'yen888@gmail.com'),
                        ('Q7R77', 'Hoàng Văn An', 18, 'Phú Yên', 'an999@gmail.com'),
                        ('R8S78', 'Vũ Thị Bình', 18, 'Gia Lai', 'binh120@gmail.com'),
                        ('S9T79', 'Đặng Văn Cường', 18, 'Kon Tum', 'cuong231@gmail.com'),
                        ('T0U80', 'Bùi Thị Dung', 18, 'Sóc Trăng', 'dung342@gmail.com'),
                        ('U1V81', 'Đỗ Văn Giang', 18, 'Cà Mau', 'giang453@gmail.com'),
                        ('V2W82', 'Hồ Thị Hải', 18, 'Bạc Liêu', 'hai564@gmail.com'),
                        ('W3X83', 'Ngô Văn Hùng', 18, 'Trà Vinh', 'hung675@gmail.com'),
                        ('X4Y84', 'Dương Thị Hương', 18, 'Vĩnh Long', 'huong786@gmail.com'),
                        ('Y5Z85', 'Lý Văn Khoa', 18, 'Hậu Giang', 'khoa897@gmail.com'),
                        ('Z6A86', 'Đoàn Thị Lâm', 18, 'Đồng Tháp', 'lam008@gmail.com'),
                        ('A7B87', 'Trịnh Văn Linh', 18, 'Bà Rịa - Vũng Tàu', 'linh119@gmail.com'),
                        ('B8C88', 'Mai Thị Mai', 18, 'Bình Thuận', 'mai230@gmail.com'),
                        ('C9D89', 'Phan Văn Nam', 18, 'Ninh Thuận', 'nam341@gmail.com'),
                        ('D0E90', 'Nguyễn Thị Nga', 18, 'Bình Phước', 'nga452@gmail.com'),
                        ('E1F91', 'Trần Văn Phong', 18, 'Tây Ninh', 'phong563@gmail.com'),
                        ('F2G92', 'Lê Thị Phương', 18, 'Hưng Yên', 'phuong674@gmail.com'),
                        ('G3H93', 'Phạm Văn Quân', 18, 'Hà Nam', 'quan785@gmail.com'),
                        ('H4I94', 'Hoàng Thị Quyên', 18, 'Ninh Bình', 'quyen896@gmail.com'),
                        ('I5J95', 'Vũ Văn Sơn', 18, 'Hòa Bình', 'son007@gmail.com'),
                        ('J6K96', 'Đặng Thị Tâm', 18, 'Sơn La', 'tam118@gmail.com'),
                        ('K7L97', 'Bùi Văn Thái', 18, 'Điện Biên', 'thai229@gmail.com'),
                        ('L8M98', 'Đỗ Thị Thảo', 18, 'Lai Châu', 'thao340@gmail.com'),
                        ('M9N99', 'Hồ Văn Thịnh', 18, 'Lào Cai', 'thinh451@gmail.com'),
                        ('N0O00', 'Ngô Thị Thu', 18, 'Yên Bái', 'thu562@gmail.com'),
                        ('O1P01', 'Dương Văn Tiến', 18, 'Thái Nguyên', 'tien673@gmail.com'),
                        ('P2Q02', 'Lý Thị Trang', 18, 'Bắc Giang', 'trang784@gmail.com'),
                        ('Q3R03', 'Đoàn Văn Tú', 18, 'Phú Thọ', 'tu895@gmail.com'),
                        ('R4S04', 'Trịnh Thị Vân', 18, 'Tuyên Quang', 'van006@gmail.com'),
                        ('S5T05', 'Mai Văn Vinh', 18, 'Hà Giang', 'vinh117@gmail.com'),
                        ('T6U06', 'Phan Thị Yến', 18, 'Cao Bằng', 'yen228@gmail.com'),
                        ('U7V07', 'Nguyễn Văn An', 18, 'Lạng Sơn', 'an339@gmail.com'),
                        ('V8W08', 'Trần Thị Bình', 18, 'Bắc Kạn', 'binh450@gmail.com'),
                        ('W9X09', 'Lê Văn Cường', 18, 'Quảng Bình', 'cuong561@gmail.com'),
                        ('X0Y10', 'Phạm Thị Dung', 18, 'Quảng Trị', 'dung672@gmail.com'),
                        ('Y1Z11', 'Hoàng Văn Giang', 18, 'Hà Nội', 'giang783@gmail.com'),
                        ('Z2A12', 'Vũ Thị Hải', 18, 'TP. Hồ Chí Minh', 'hai894@gmail.com'),
                        ('A3B13', 'Đặng Văn Hùng', 18, 'Đà Nẵng', 'hung005@gmail.com'),
                        ('B4C14', 'Bùi Thị Hương', 18, 'Nghệ An', 'huong116@gmail.com'),
                        ('C5D15', 'Đỗ Văn Khánh', 18, 'Thanh Hóa', 'khanh227@gmail.com'),
                        ('D6E16', 'Hồ Thị Lan', 18, 'Hải Phòng', 'lan338@gmail.com'),
                        ('E7F17', 'Ngô Văn Linh', 18, 'Thừa Thiên Huế', 'linh449@gmail.com'),
                        ('F8G18', 'Dương Thị Mai', 18, 'Cần Thơ', 'mai560@gmail.com'),
                        ('G9H19', 'Lý Văn Nam', 18, 'Quảng Ninh', 'nam671@gmail.com'),
                        ('H0I20', 'Đoàn Thị Nga', 18, 'Đắk Lắk', 'nga782@gmail.com'),
                        ('I1J21', 'Trịnh Văn Phong', 18, 'Lâm Đồng', 'phong893@gmail.com'),
                        ('J2K22', 'Mai Thị Phương', 18, 'Đồng Nai', 'phuong004@gmail.com'),
                        ('K3L23', 'Phan Văn Quân', 18, 'Bình Dương', 'quan115@gmail.com'),
                        ('L4M24', 'Nguyễn Thị Quyên', 18, 'Khánh Hòa', 'quyen226@gmail.com'),
                        ('M5N25', 'Trần Văn Sơn', 18, 'Hà Tĩnh', 'son337@gmail.com'),
                        ('N6O26', 'Lê Thị Thảo', 18, 'Thái Bình', 'thao448@gmail.com'),
                        ('O7P27', 'Phạm Văn Thịnh', 18, 'Nam Định', 'thinh559@gmail.com'),
                        ('P8Q28', 'Hoàng Thị Trang', 18, 'Bắc Ninh', 'trang670@gmail.com'),
                        ('Q9R29', 'Vũ Văn Tuấn', 18, 'Vĩnh Phúc', 'tuan781@gmail.com'),
                        ('R0S30', 'Đặng Thị Tuyết', 18, 'Hải Dương', 'tuyet892@gmail.com'),
                        ('S1T31', 'Bùi Văn Vinh', 18, 'Kiên Giang', 'vinh003@gmail.com'),
                        ('T2U32', 'Đỗ Thị Yến', 18, 'An Giang', 'yen114@gmail.com'),
                        ('U3V33', 'Hồ Văn Anh', 18, 'Tiền Giang', 'anh225@gmail.com'),
                        ('V4W34', 'Ngô Thị Bảo', 18, 'Long An', 'bao336@gmail.com'),
                        ('W5X35', 'Dương Văn Cường', 18, 'Bến Tre', 'cuong447@gmail.com'),
                        ('X6Y36', 'Lý Thị Dung', 18, 'Quảng Nam', 'dung558@gmail.com'),
                        ('Y7Z37', 'Đoàn Văn Đức', 18, 'Quảng Ngãi', 'duc669@gmail.com'),
                        ('Z8A38', 'Trịnh Thị Giang', 18, 'Bình Định', 'giang780@gmail.com'),
                        ('A9B39', 'Mai Văn Hải', 18, 'Phú Yên', 'hai891@gmail.com'),
                        ('B0C40', 'Phan Thị Hoa', 18, 'Gia Lai', 'hoa002@gmail.com'),
                        ('C1D41', 'Nguyễn Văn Hùng', 18, 'Kon Tum', 'hung113@gmail.com'),
                        ('D2E42', 'Trần Thị Hương', 18, 'Sóc Trăng', 'huong224@gmail.com'),
                        ('E3F43', 'Lê Văn Khoa', 18, 'Cà Mau', 'khoa335@gmail.com'),
                        ('F4G44', 'Phạm Thị Lâm', 18, 'Bạc Liêu', 'lam446@gmail.com'),
                        ('G5H45', 'Hoàng Văn Linh', 18, 'Trà Vinh', 'linh557@gmail.com'),
                        ('H6I46', 'Vũ Thị Mai', 18, 'Vĩnh Long', 'mai668@gmail.com'),
                        ('I7J47', 'Đặng Văn Nam', 18, 'Hậu Giang', 'nam779@gmail.com'),
                        ('J8K48', 'Bùi Thị Nga', 18, 'Đồng Tháp', 'nga890@gmail.com'),
                        ('K9L49', 'Đỗ Văn Phong', 18, 'Bà Rịa - Vũng Tàu', 'phong001@gmail.com'),
                        ('L0M50', 'Hồ Thị Phương', 18, 'Bình Thuận', 'phuong112@gmail.com'),
                        ('M1N51', 'Ngô Văn Quân', 18, 'Ninh Thuận', 'quan223@gmail.com'),
                        ('N2O52', 'Dương Thị Quyên', 18, 'Bình Phước', 'quyen334@gmail.com'),
                        ('O3P53', 'Lý Văn Sơn', 18, 'Tây Ninh', 'son445@gmail.com'),
                        ('P4Q54', 'Đoàn Thị Thảo', 18, 'Hưng Yên', 'thao556@gmail.com'),
                        ('Q5R55', 'Trịnh Văn Thịnh', 18, 'Hà Nam', 'thinh667@gmail.com'),
                        ('R6S56', 'Mai Thị Trang', 18, 'Ninh Bình', 'trang778@gmail.com'),
                        ('S7T57', 'Phan Văn Tuấn', 18, 'Hòa Bình', 'tuan889@gmail.com'),
                        ('T8U58', 'Nguyễn Thị Tuyết', 18, 'Sơn La', 'tuyet000@gmail.com'),
                        ('U9V59', 'Trần Văn Vinh', 18, 'Điện Biên', 'vinh111@gmail.com'),
                        ('V0W60', 'Lê Thị Yến', 18, 'Lai Châu', 'yen222@gmail.com');

                        
                        INSERT INTO course (courseName, majorId) VALUES 
                        ('Lập trình C++'            ,1),
                        ('Cơ sở dữ liệu'            ,1),
                        ('Mạng máy tính'            ,1),
                        ('Quản trị chuỗi cung ứng'  ,2),
                        ('Vận tải đa phương thức'   ,2),
                        ('Quản lý kho vận'          ,2);

                        INSERT INTO major(majorName) VALUES 
                        ('CNTT'),
                        ('Logictic');

                        )";
    
    run = sqlite3_exec(db, sql, 0, 0, &errMsg);
    
    if (run != SQLITE_OK)
    {
        cout << "Error: " << errMsg << endl;
    };
    
    sqlite3_close(db);

}